import {
  Home,
  Contact,
  About,
  Cart,
  WishList,
  Checkout,
  UserApp,
  Profile,
  General,
  MyOrders,
  MyAccounts,
  Security,
  ManageCards,
  MyProducts,
} from "../components";
export default [
  {
    name: "Home",
    id: 0,
    link: "/home",
    isMenu: true,
    component: Home,
    default: true,
    isUserMenu: false,
    isActive: true,
  },
  {
    name: "About",
    id: 1,
    link: "/about",
    isMenu: true,
    component: About,
    isUserMenu: false,
  },
  {
    name: "Contact",
    id: 2,
    link: "/contact",
    isMenu: true,
    component: Contact,
    isUserMenu: false,
  },
  {
    name: "Cart",
    id: 3,
    link: "/cart",
    isMenu: false,
    component: Checkout,
    isSecured: true,
    isUserMenu: false,
  },
  {
    name: "WishList",
    id: 4,
    link: "/wishlist",
    isMenu: false,
    component: WishList,
    isSecured: true,
    isUserMenu: false,
  },
  {
    name: "auth",
    id: 6,
    link: "/auth",
    isMenu: false,
    component: UserApp,
    isUserMenu: false,
  },
  {
    name: "Profile",
    id: 7,
    link: "/profile/general",
    isMenu: false,
    component: Profile,
    isUserMenu: true,
    childrens: [
      {
        name: "General",
        id: 7,
        link: "/profile/general",
        isMenu: false,
        component: General,
        isUserMenu: false,
        childrens: [],
      },
      {
        name: "Security",
        id: 7.2,
        link: "/profile/security",
        isMenu: false,
        component: Security,
        isUserMenu: false,
        childrens: [],
      },
      {
        name: "Manage Cards",
        id: 7.3,
        link: "/profile/managecards",
        isMenu: false,
        component: ManageCards,
        isUserMenu: false,
        childrens: [],
      },
      {
        name: "My Orders",
        id: 7.4,
        link: "/profile/myorders",
        isMenu: false,
        component: MyOrders,
        isUserMenu: false,
        childrens: [],
      },
      {
        name: "My Account",
        id: 7.5,
        link: "/profile/myaccounts",
        isMenu: false,
        component: MyAccounts,
        isUserMenu: false,
        childrens: [],
      },
      {
        name: "My Products",
        id: 7.6,
        link: "/profile/myproducts",
        isMenu: false,
        component: MyProducts,
        isUserMenu: false,
        childrens: [],
        isPremium: true,
      },
    ],
  },
];
